version: '3.9'

services:
  frontend:
    container_name: docker_frontend
    build: ./frontend
    ports:
      - "81:80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/

  backend:
    container_name: docker_backend
    build: ./backend 
    ports:
      - "82:80"
    volumes:
      - ./backend:/usr/local/apache2/htdocs/
      - ./backend/BDD:/app/BDD

  dbviewer:
    image: lscr.io/linuxserver/sqlitebrowser
    container_name: sqlite_viewer
    ports:
      - "83:3000"
    volumes:
      - ./backend/BDD:/db.sqlite
    depends_on:
      - backend
